import { allFrames, coversEyes, exprKeys, toEnglish, wheelButton, type FiguraConfig } from '../skin/figura'
import type { HairInfo } from '../skin/hair'
import type { ModelInfo } from './bbmodel'

const lua = (n: number) => String(Math.round(n * 1000) / 1000)
const path = (p: string[]) => 'M.' + p.join('.')
/** User text inside a Lua string: English only, no quotes/backslashes. */
const str = (s: string, fallback: string) => toEnglish(s).replace(/["\\]/g, '') || fallback
const isEmoji = (icon: string) => /^:[\w@+-]+:$/.test(icon.trim())
/** Item ids only: letters, digits, _ . : / - */
const item = (icon: string) => (/^[a-z0-9_.:/-]+$/.test(icon.trim()) ? icon.trim() : 'minecraft:name_tag')

/** Generate script.lua for the avatar. Everything exported is English-only by design. */
export function buildScript(name: string, cfg: FiguraConfig, info: ModelInfo, hair: HairInfo[]): string {
  const out: string[] = []
  const add = (...l: string[]) => out.push(...l)
  const frames = Object.keys(info.faceParts)
  const has = (f: string) => frames.includes(f)

  add(
    `-- ${str(name, 'Avatar')} - generated by NKW Skin & Figura Custom`,
    '-- Feel free to edit. Re-exporting from the app overwrites this file.',
    'local M = models.model',
    ...(cfg.hideVanilla === 'all'
      ? ['vanilla_model.PLAYER:setVisible(false)']
      : ['-- only hide the vanilla parts this avatar replaces, so it merges with other avatars', ...info.replaces.map((p) => `vanilla_model.${p}:setVisible(false)`)]),
    ''
  )

  // ---- hair physics ----------------------------------------------------------------------
  const chains = cfg.hairPhysics ? info.hairChains : []
  if (chains.length) {
    add('local phys = require("nkw_physics")')
    for (const c of chains) {
      const h = hair.find((x) => x.id === c.id)
      if (!h) continue
      const parts = c.path.slice(1).map((_, i) => path(['Head', ...c.path.slice(0, i + 2)]))
      const p = h.phys
      add(
        `phys.chain({ ${parts.join(', ')} }, { side = "${h.side}", stiffness = ${lua(p.stiffness)}, damping = ${lua(p.damping)}, gravity = ${lua(p.gravity)}, drag = ${lua(p.drag)}, sway = ${lua(p.sway)}, limitIn = ${lua(p.limitIn)}, limitOut = ${lua(p.limitOut)}, axis = ${cfg.swingAxis} })`
      )
    }
    add('')
  }

  // ---- face frames ---------------------------------------------------------------------
  add('local face = {')
  for (const f of frames) add(`  ${f} = M.Head.Face.${info.faceParts[f as keyof typeof info.faceParts]},`)
  add('}', 'for _, p in pairs(face) do p:setVisible(false) end')
  add(
    'local state = { expr = nil, blink = false, talk = false }',
    `local covers = { ${allFrames(cfg).filter((f) => coversEyes(f, cfg)).map((f) => `${f} = true`).join(', ')} }`,
    'local function refresh()',
    '  for k, p in pairs(face) do',
    '    if k ~= "blink" and k ~= "talk" then p:setVisible(state.expr == k) end',
    '  end',
    '  -- no blinking over an expression that draws its own (closed) eyes',
    '  if face.blink then face.blink:setVisible(state.blink and not (state.expr and covers[state.expr])) end',
    '  if face.talk then face.talk:setVisible(state.talk) end',
    'end',
    ''
  )

  // ---- expressions (action wheel, synced with pings) ------------------------------------
  const exprs = exprKeys(cfg).filter(has)
  if (cfg.expressions && exprs.length) {
    add(
      `local EXPR = { ${exprs.map((e) => `"${e}"`).join(', ')} }`,
      'function pings.nkwExpr(i)',
      '  local e = EXPR[i]',
      '  state.expr = (state.expr ~= e) and e or nil',
      '  refresh()',
      'end'
    )
    const buttons = exprs.map((e) => {
      const b = wheelButton(cfg, e)
      return { title: str(b.title, 'Expression'), icon: b.icon.trim() }
    })
    if (cfg.wheel === 'auria') {
      // Auria's wheel (MIT, AuriaFoxGirl): animated wheel, supports emoji icons
      add('local wheel = require("auria_wheel.main")', 'local page = wheel.newPage()', 'wheel.setPage(page)')
      buttons.forEach((b, i) => {
        const icon = isEmoji(b.icon) ? `:setIconEmoji("${b.icon}")` : `:setIconItem("${item(b.icon)}")`
        add(`page:newAction():setTitle("${b.title}")${icon}:onPress(function() pings.nkwExpr(${i + 1}) end)`)
      })
      add('')
    } else {
      add('if host:isHost() then', '  local page = action_wheel:newPage("Expressions")')
      buttons.forEach((b, i) => add(`  page:newAction():title("${b.title}"):item("${isEmoji(b.icon) ? 'minecraft:name_tag' : item(b.icon)}"):onLeftClick(function() pings.nkwExpr(${i + 1}) end)`))
      add('  action_wheel:setPage(page)', 'end', '')
    }
  }

  // ---- tick: blink + talking ---------------------------------------------------------------
  const blink = cfg.blink && has('blink')
  const talk = cfg.talk && has('talk')
  if (blink || talk) {
    add('local blinkIn, blinkLeft, flap = 60, 0, 0', 'function events.tick()')
    if (blink)
      add(
        '  if blinkLeft > 0 then',
        '    blinkLeft = blinkLeft - 1',
        '    if blinkLeft == 0 then state.blink = false; refresh() end',
        '  else',
        '    blinkIn = blinkIn - 1',
        '    if blinkIn <= 0 then',
        '      state.blink, blinkLeft = true, 3',
        `      blinkIn = math.random(${Math.round(cfg.blinkMin * 20)}, ${Math.round(cfg.blinkMax * 20)})`,
        '      refresh()',
        '    end',
        '  end'
      )
    if (talk)
      add(
        '  -- talking needs Plasmo Voice + the FigExtra addon (global "plasmovoice") on the viewer',
        '  local talking = false',
        '  if plasmovoice then',
        '    local ok, lvl = pcall(function() return plasmovoice:getVoiceLevel(player:getUUID()) end)',
        `    talking = ok and lvl ~= nil and lvl > ${lua(cfg.talkThreshold)}`,
        '  end',
        '  flap = talking and (flap + 1) % 4 or 0',
        '  local open = talking and flap < 2',
        '  if open ~= state.talk then state.talk = open; refresh() end'
      )
    add('end', '')
  }

  // ---- render: smooth head ------------------------------------------------------------------
  if (cfg.smoothHead) {
    add(
      'local sm, last = nil, client.getSystemTime()',
      'local function wrap(a) return (a + 180) % 360 - 180 end',
      'function events.render(delta, ctx)',
      '  if ctx ~= "RENDER" and ctx ~= "FIRST_PERSON" then return end',
      '  local now = client.getSystemTime()',
      '  local dt = math.min((now - last) / 50, 4) -- in ticks',
      '  last = now',
      '  local target = vanilla_model.HEAD:getOriginRot()',
      '  sm = sm or target',
      `  local f = 1 - (1 - ${lua(cfg.headSpeed)}) ^ dt`,
      '  sm = sm + vec(wrap(target.x - sm.x), wrap(target.y - sm.y), wrap(target.z - sm.z)) * f',
      '  M.Head:setRot(vec(wrap(sm.x - target.x), wrap(sm.y - target.y), wrap(sm.z - target.z)))',
      'end',
      ''
    )
  }
  add('refresh()')
  return out.join('\n') + '\n'
}
