import { allFrames, coversEyes, itemView, liveWheel, toEnglish, wheelScreens, type FiguraConfig, type WheelIcon } from '../skin/figura'
import { hairOpts, livePhys, strandVariation, type HairInfo } from '../skin/hair'
import type { ModelInfo } from './bbmodel'

const lua = (n: number) => String(Math.round(n * 1000) / 1000)
const path = (p: string[]) => 'M.' + p.join('.')
/** User text inside a Lua string: English only, no quotes/backslashes. */
const str = (s: string, fallback: string) => toEnglish(s).replace(/["\\]/g, '') || fallback
/** Item ids only: letters, digits, _ . : / - */
const item = (id: string) => (/^[a-z0-9_.:/-]+$/.test(id.trim()) ? id.trim() : 'minecraft:name_tag')
const emoji = (t: string) => (/^:[\w@+-]+:$/.test(t.trim()) ? t.trim() : ':question:')
const colour = (hex?: string) => {
  const m = hex && /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex)
  return m ? `vec(${[m[1], m[2], m[3]].map((h) => lua(parseInt(h, 16) / 255)).join(', ')})` : null
}

/** auria_wheel/conf.lua with the chosen look and feel. */
export function auriaConf(cfg: FiguraConfig): string {
  const a = cfg.auriaStyle
  const c = colour(a.overlay) ?? 'vec(0.2, 0.22, 0.25)'
  return [
    '-- generated by NKW Skin & Figura Custom (auria wheel settings)',
    '---@class auria.wheel.config <partial>',
    'local conf = {',
    '   keybind = keybinds:fromVanilla("figura.config.action_wheel_button"),',
    `   overlayColor = vec(${c.slice(4, -1)}, ${lua(Math.min(1, Math.max(0, a.overlayAlpha)))}),`,
    `   postEffect = ${a.blur ? '"blur"' : 'nil'},`,
    `   mode = "${['HOLD', 'MIXED', 'TOGGLE'].includes(a.mode) ? a.mode : 'MIXED'}",`,
    `   holdTime = ${Math.round(Math.min(2000, Math.max(50, a.holdTime)))},`,
    `   animationSpeed = ${lua(Math.min(1, Math.max(0.05, a.animationSpeed)))},`,
    `   noAnimations = ${a.animations ? 'false' : 'true'},`,
    '   backHint = "Right click: back", -- shown on sub pages (NKW addition)',
    '}',
    'return conf',
    ''
  ].join('\n')
}

/** Generate script.lua for the avatar. Everything exported is English-only by design. */
export function buildScript(name: string, cfg: FiguraConfig, info: ModelInfo, hair: HairInfo[]): string {
  const out: string[] = []
  const add = (...l: string[]) => out.push(...l)
  const frames = Object.keys(info.faceParts)
  const has = (f: string) => frames.includes(f)

  add(
    `-- ${str(name, 'Avatar')} - generated by NKW Skin & Figura Custom`,
    '-- Feel free to edit. Re-exporting from the app overwrites this file.',
    'local M = models.model',
    ...(cfg.hideVanilla === 'all' && cfg.skinParts === 'all'
      ? ['vanilla_model.PLAYER:setVisible(false)']
      : ['-- only hide the vanilla parts this avatar replaces, so it merges with other avatars', ...info.replaces.map((p) => `vanilla_model.${p}:setVisible(false)`)]),
    ''
  )

  // ---- hair physics ----------------------------------------------------------------------
  const chains = cfg.hairPhysics ? info.hairChains : []
  if (chains.length) {
    add('local phys = require("nkw_physics")')
    for (const c of chains) {
      const h = hair.find((x) => x.id === c.id)
      if (!h) continue
      // every group on the path from the first segment down (a strand group sits above them)
      const first = c.path.findIndex((x) => /^s\d+$/.test(x))
      const parts = c.path.slice(first).map((_, i) => path(['Head', ...c.path.slice(0, first + i + 1)]))
      const o = hairOpts(h)
      const p = livePhys(h.phys, o.hang)
      const v = strandVariation(c.strand ?? 0, c.strands ?? 1)
      const flow = o.flutter ? `, flutter = ${lua(o.flutter)}, phase = ${lua(v.phase)}` : ''
      add(
        `phys.chain({ ${parts.join(', ')} }, { side = "${h.side}", stiffness = ${lua(p.stiffness * (1 + v.jitter))}, gravity = ${lua(p.gravity)}, drag = ${lua(p.drag)}, sway = ${lua(p.sway)}, limitIn = ${lua(p.limitIn)}, limitOut = ${lua(p.limitOut)}, axis = ${cfg.swingAxis}${flow} })`
      )
    }
    add('')
  }

  // ---- face frames ---------------------------------------------------------------------
  add('local face = {')
  for (const f of frames) add(`  ${f} = M.Head.Face.${info.faceParts[f as keyof typeof info.faceParts]},`)
  add('}', 'for _, p in pairs(face) do p:setVisible(false) end')
  add(
    'local state = { expr = nil, blink = false, talk = false }',
    '-- features the action wheel can switch off',
    'local toggles = { blink = true, physics = true, smoothHead = true, talk = true }',
    ...(info.glow?.eyes ? ['local glowEyes = M.Head.Face.GlowEyes'] : []),
    `local covers = { ${allFrames(cfg).filter((f) => coversEyes(f, cfg)).map((f) => `${f} = true`).join(', ')} }`,
    'local function refresh()',
    '  for k, p in pairs(face) do',
    '    if k ~= "blink" and k ~= "talk" and k ~= "base" then p:setVisible(state.expr == k) end',
    '  end',
    '  -- no blinking over an expression that draws its own (closed) eyes',
    '  if face.blink then face.blink:setVisible(state.blink and not (state.expr and covers[state.expr])) end',
    '  if face.talk then face.talk:setVisible(state.talk) end',
    '  -- the base frame replaces the skin face and stays under everything',
    '  if face.base then face.base:setVisible(true) end',
    ...(info.glow?.eyes
      ? ['  -- glowing eyes go dark while the eyes are closed or an expression draws its own', '  glowEyes:setVisible(not state.blink and not (state.expr and covers[state.expr]))']
      : []),
    'end',
    ''
  )

  // ---- action wheel (pages of expressions and toggles, synced with pings) ----------------
  const pages = liveWheel(cfg, { frames: has, physics: chains.length > 0, glow: info.glow })
  const live = pages.filter((p, i) => i === 0 || pages.some((q) => q.items.some((it) => (it.type === 'page' || it.type === 'home') && it.page === p.id)))
  if (live[0]?.items.length) {
    const exprs = live.flatMap((p) => p.items.filter((it) => it.type === 'expr').map((it) => it.expr!))
    const usedToggles = [...new Set(live.flatMap((p) => p.items.filter((it) => it.type === 'toggle').map((it) => it.toggle!)))]
    if (exprs.length)
      add(
        `local EXPR = { ${exprs.map((e) => `"${e}"`).join(', ')} }`,
        'function pings.nkwExpr(i)',
        '  local e = EXPR[i]',
        '  state.expr = (e and state.expr ~= e) and e or nil',
        '  refresh()',
        'end'
      )
    if (usedToggles.length) {
      const glowParts = (t: string): string[] => {
        const g = info.glow
        if (!g) return []
        const eyes = g.eyes ? ['M.Head.Face.GlowEyes'] : []
        const skin = g.skin ? g.skinParts.map((p) => 'M.' + p) : []
        const hair = (id: string) => (info.hairGroups?.[id] ? ['M.Head.' + info.hairGroups[id]] : [])
        if (t === 'glow') return [...eyes, ...skin, ...g.hair.flatMap(hair)]
        if (t === 'glowEyes') return eyes
        if (t === 'glowSkin') return skin
        return hair(t.slice(9))
      }
      const apply: Record<string, string> = {
        blink: 'if not on then state.blink = false; refresh() end',
        talk: 'if not on then state.talk = false; refresh() end',
        physics: 'phys.setEnabled(on)',
        smoothHead: 'if not on then M.Head:setRot(0, 0, 0) end',

      }
      add(
        `local TOGGLE = { ${usedToggles.map((t) => `"${t}"`).join(', ')} }`,
        'function pings.nkwToggle(i, on)',
        '  local k = TOGGLE[i]',
        '  if not k then return end',
        '  toggles[k] = on',
        ...usedToggles.map(
          (t, i) => `  ${i ? 'elseif' : 'if'} k == "${t}" then ${t.startsWith('glow') ? `for _, p in ipairs({ ${glowParts(t).join(', ')} }) do p:setSecondaryRenderType(on and "EMISSIVE" or "NONE") end` : apply[t]}`
        ),
        '  end',
        'end'
      )
    }
    const auria = cfg.wheel === 'auria'
    const needsTex = live.some((p) => p.items.some((it) => ['image', 'face'].includes(itemView(cfg, it).icon.kind)))
    if (needsTex) add('local TEX = textures["model.skin"] or textures:getTextures()[1]')
    /** Icon call for an action; images and faces come from the avatar texture. */
    const icon = (ic: WheelIcon, id: string): string => {
      // uploads and faces are baked into the atlas as icon_<id>; a face can also use its frame slot
      const slot = ic.kind === 'image' || ic.kind === 'face' ? (info.atlas.slots['icon_' + id] ?? (ic.kind === 'face' ? info.atlas.slots['face_' + ic.frame] : undefined)) : undefined
      if (slot) return auria ? `:setIconTexture(TEX, vec(${slot.x}, ${slot.y}), vec(${slot.w}, ${slot.h}))` : `:texture(TEX, ${slot.x}, ${slot.y}, ${slot.w}, ${slot.h}, ${lua(16 / slot.w)})`
      if (ic.kind === 'emoji') return auria ? `:setIconEmoji("${emoji(ic.text)}")` : ':item("minecraft:name_tag")'
      const id2 = item(ic.kind === 'item' ? ic.id : 'minecraft:name_tag')
      return auria ? `:setIconItem("${id2}")` : `:item("${id2}")`
    }

    if (auria) {
      // Auria's wheel (MIT, AuriaFoxGirl): animated, breadcrumbs, right click goes back (a hint says so),
      // so long pages only get a "Next" button
      const screens = wheelScreens(live, (p) => Math.max(2, Math.round(p.groupSize || 8)), false)
      const close = cfg.auriaStyle.closeOnExpr !== false ? ' wheel.setEnabled(false)' : ''
      add('local wheel = require("auria_wheel.main")', 'local P = {}')
      screens.forEach((sc, i) => add(`P[${i + 1}] = wheel.newPage():setTitle("${str(sc.title, 'Page')}${sc.parts > 1 ? ` ${sc.part + 1}/${sc.parts}` : ''}")`))
      screens.forEach((sc, i) => {
        const head = `P[${i + 1}]`
        for (const sl of sc.slots) {
          if (sl.kind === 'next') add(`${head}:newAction():setTitle("Next"):setIconItem("minecraft:spectral_arrow"):setPage(P[${sl.to + 1}])`)
          if (sl.kind !== 'item') continue
          const it = sl.item
          const v = itemView(cfg, it)
          const t = `:setTitle("${str(v.title, 'Action')}")${icon(v.icon, it.id)}`
          if (it.type === 'toggle') add(`${head}:newToggle()${t}:setToggled(true):onToggle(function(on) pings.nkwToggle(${usedToggles.indexOf(it.toggle!) + 1}, on) end)`)
          else if (sl.to !== undefined) add(`${head}:newAction()${t}:setPage(P[${sl.to + 1}])`)
          else add(`${head}:newAction()${t}:onPress(function() pings.nkwExpr(${it.type === 'clear' ? 0 : exprs.indexOf(it.expr!) + 1})${close} end)`)
        }
      })
      add('wheel.setPage(P[1])', '')
    } else {
      // pages of 8 with Back / Next buttons (Figura's wheel has no back of its own)
      const screens = wheelScreens(live)
      add('if host:isHost() then', '  local P = {}')
      screens.forEach((sc, i) => add(`  P[${i + 1}] = action_wheel:newPage("${str(sc.title, 'Page')}${sc.parts > 1 ? ` ${sc.part + 1}/${sc.parts}` : ''}")`))
      const go = (to: number) => `:onLeftClick(function() action_wheel:setPage(P[${to + 1}]) end)`
      screens.forEach((sc, i) => {
        for (const sl of sc.slots) {
          const head = `  P[${i + 1}]:newAction()`
          if (sl.kind === 'back') add(`${head}:title("Back"):item("minecraft:arrow")${go(sl.to)}`)
          else if (sl.kind === 'next') add(`${head}:title("Next"):item("minecraft:spectral_arrow")${go(sl.to)}`)
          else {
            const it = sl.item
            const v = itemView(cfg, it)
            const c = colour(v.color)
            const t = `${head}:title("${str(v.title, 'Action')}")${icon(v.icon, it.id)}${c ? `:setColor(${c})` : ''}`
            if (it.type === 'toggle') add(`${t}:setToggled(true):onToggle(function(on) pings.nkwToggle(${usedToggles.indexOf(it.toggle!) + 1}, on) end)`)
            else if (sl.to !== undefined) add(t + go(sl.to))
            else add(`${t}:onLeftClick(function() pings.nkwExpr(${it.type === 'clear' ? 0 : exprs.indexOf(it.expr!) + 1}) end)`)
          }
        }
      })
      add('  action_wheel:setPage(P[1])', 'end', '')
    }
  }

  // ---- tick: blink + talking ---------------------------------------------------------------
  const blink = cfg.blink && has('blink')
  const talk = cfg.talk && has('talk')
  if (blink || talk) {
    add('local blinkIn, blinkLeft, flap = 60, 0, 0', 'function events.tick()')
    if (blink)
      add(
        '  if not toggles.blink then',
        '    -- blinking switched off from the wheel',
        '  elseif blinkLeft > 0 then',
        '    blinkLeft = blinkLeft - 1',
        '    if blinkLeft == 0 then state.blink = false; refresh() end',
        '  else',
        '    blinkIn = blinkIn - 1',
        '    if blinkIn <= 0 then',
        '      state.blink, blinkLeft = true, 3',
        `      blinkIn = math.random(${Math.round(cfg.blinkMin * 20)}, ${Math.round(cfg.blinkMax * 20)})`,
        '      refresh()',
        '    end',
        '  end'
      )
    if (talk)
      add(
        '  -- talking needs Plasmo Voice + the FigExtra addon (global "plasmovoice") on the viewer',
        '  local talking = false',
        '  if plasmovoice and toggles.talk then',
        '    local ok, lvl = pcall(function() return plasmovoice:getVoiceLevel(player:getUUID()) end)',
        `    talking = ok and lvl ~= nil and lvl > ${lua(cfg.talkThreshold)}`,
        '  end',
        '  flap = talking and (flap + 1) % 4 or 0',
        '  local open = talking and flap < 2',
        '  if open ~= state.talk then state.talk = open; refresh() end'
      )
    add('end', '')
  }

  // ---- render: smooth head ------------------------------------------------------------------
  if (cfg.smoothHead) {
    add(
      'local sm, last = nil, client.getSystemTime()',
      ...(chains.length ? ['-- hair reacts to the lagging head, so the two move together', `phys.followHead(${lua(cfg.headSpeed)})`] : []),
      'local function wrap(a) return (a + 180) % 360 - 180 end',
      'function events.render(delta, ctx)',
      '  if ctx ~= "RENDER" and ctx ~= "FIRST_PERSON" then return end',
      '  if not toggles.smoothHead then return end',
      '  local now = client.getSystemTime()',
      '  local dt = math.min((now - last) / 50, 4) -- in ticks',
      '  last = now',
      '  local target = vanilla_model.HEAD:getOriginRot()',
      '  sm = sm or target',
      `  local f = 1 - (1 - ${lua(cfg.headSpeed)}) ^ dt`,
      '  sm = sm + vec(wrap(target.x - sm.x), wrap(target.y - sm.y), wrap(target.z - sm.z)) * f',
      ...(cfg.headTilt
        ? [`  -- tilt a little into the turn while the head is catching up`, `  local tilt = math.max(-1, math.min(1, wrap(target.y - sm.y) / 15)) * ${lua(cfg.headTilt)}`]
        : ['  local tilt = 0']),
      '  M.Head:setRot(vec(wrap(sm.x - target.x), wrap(sm.y - target.y), wrap(sm.z - target.z) + tilt))',
      'end',
      ''
    )
  }
  add('refresh()')
  return out.join('\n') + '\n'
}
